grid_search:
  class: GridSearchCV
  module: sklearn.model_selection
  params:
    cv: 2
    verbose: 1
    n_jobs: -1

model_selection:
  module_0:
    class: RandomForestClassifier
    module: sklearn.ensemble
    params:
      random_state: 42
    search_param_grid:
      n_estimators: [100, 200]
      max_depth: [5, 10, 15]
      min_samples_split: [2, 5]
      min_samples_leaf: [1, 2]

  module_1:
    class: GradientBoostingClassifier
    module: sklearn.ensemble
    params:
      random_state: 42
    search_param_grid:
      learning_rate: [0.05, 0.1]
      n_estimators: [100, 200]
      max_depth: [3, 5]
      subsample: [0.8, 1.0]

  # Optional: Add more models here
  # module_2:
  #   class: LogisticRegression
  #   module: sklearn.linear_model
  #   params:
  #     random_state: 42
  #   search_param_grid:
  #     C: [0.1, 1.0, 10.0]
  #     penalty: ["l2"]
  #     solver: ["lbfgs", "liblinear"]

  # module_3:
  #   class: XGBClassifier
  #   module: xgboost
  #   params:
  #     random_state: 42
  #   search_param_grid:
  #     n_estimators: [100, 200]
  #     max_depth: [3, 5, 7]
  #     learning_rate: [0.01, 0.1, 0.3]
  #     subsample: [0.8, 1.0]
